= Notes 

== Week1 AS2 ==
=== Basic summary of tensor flows usage in CNN structure ===

. *initialize weights parameter*. eg.`tf.get_variable("W", [1,2,3,4], initializer = tf.contrib.layers.xavier_initializer(seed = 0))`
. *forward propagation*, including convolution layer, pooling layer and fully connected layer
* convolution layer: conv2d and relu.
 eg.`tf.nn.conv2d(X, W1, strides=[1,1,1,1], padding='SAME')`
	  `tf.nn.relu(Z1)`
* pooling layer: max pool.
 eg.`tf.nn.max_pool(A2, ksize=[1,4,4,1], strides = [1,4,4,1], padding='SAME')`
* fully conencted: flatten(sometimes), fully_connected.
 eg.`tf.contrib.layers.flatten(P2)`,
     `tf.contrib.layers.fully_connected(P, 6, activation_fn=None )`
. *cost function*: 
  eg.`tf.reduce_mean( tf.nn.softmax_cross_entropy_with_logits(logits = Z3, labels=Y))`
. *back propagation*:optimizer.
  eg.`tf.train.AdamOptimizer(learning_rate = learning_rate).minimize(cost)`

=== Points worth attention ===
. The out put of forward propagation should be linear result *without activation fucntion*.
  This is because `softmax_cross_entropy_with_logits` will include softmax activation function and resulting loss at the same time.
. For *initialize weight parameter* part, W1:[ kernel size, kernel size, input size(channel number), output size(filters number)].

  
== Week2 AS1 ==
=== Basic summary of YOLO algorithm ===

. *Go through CNN* Input image `(608, 608, 3)`. The input image goes through a CNN, resulting in a `(19,19,5,85)` dimensional output.( (pc,bx,by,bh,bw)  has 5 numbers, and and 80 is the number of classes we would like to detect)
. *Filter through all the boxes* using non-max suppression. Specifically:
.. Score-thresholding: throw away boxes that have detected a class with a score less than the threshold
.. Non-max suppression: Compute the Intersection over Union and avoid selecting overlapping boxes

=== Implementation details of *Filter through all the boxes* ===
. element multiply *box_confidence* with *box_class_probs*, get max( ensure there is only one class for one cell, one anchor)
. get filtering mask(remove those with small prob, filter size is `(19*19*5)`
. get filtered box_confidence, boxes, box_classes(after filter, boxes, scores, classes are flattened)
. perform non-maximum suppresion to get anchor

=== Points worth mentioning ===
. when comprehensioning the variables with 4 dimensions, the first three 19*19*5 can be regarded as a block. When considering the single data, just look at the last dimension to check the vector size
. for anchor box assignment, just two numbers should be okay, which is height and weight. Becasue the anchor box doesn't need to fix the center cx, cy
